### ISSUE TITLE
Something seems missed

### ISSUE THREAD

**Issue by jerrita** [edk2-porting/MU-SM8150Pkg#17]
Following the tutorial, but something went wrong.
Any thoughts?

![image](https://user-images.githubusercontent.com/28153001/176457805-c07ddc7c-495e-4b3b-9453-e21ad54d97cf.png)
![image](https://user-images.githubusercontent.com/28153001/176457617-413d6108-4f53-439e-827f-849721b1c3fe.png)

**Comment by sunflower2333** [comment]
There is some issues with submodule (or the repo) because I seldom update it.
I can not solve it because me noob.
One solution is to decompress  env.tgz which contains "MU_BASECORE\ Common\ Silicon\".
You can find it in renegade Telegram group.
![pic](https://user-images.githubusercontent.com/54024877/176751411-bbdb4596-eb8c-4e52-bb53-d9f91119f368.png)
